"""Ensure the deployment checks have a compatible "received" database.

A fresh clone contains no database: SQLite files are gitignored and are never
committed.  When the real received file is absent, this builds a disposable
compatible fixture so the deployment preflight checks can still run.  It never
overwrites an existing file, and the fixture is never committed.
"""
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DATABASE = ROOT / 'accounting-software' / 'database.db'
MANIFEST = ROOT / 'documentation' / 'accounting-preservation.json'

_BUILD = (
    "import database, os;"
    "database.configure_database('sqlite:///' + os.environ['EID_FIXTURE_DB']);"
    "database.init_db();"
    "from models.user import User;"
    "from database import get_session;"
    "db = get_session();"
    "u = User(name='System Admin', email='admin@example.com', role='admin');"
    "u.set_password(os.environ['ADMIN_PASSWORD']);"
    "db.add(u); db.commit(); db.close()"
)


def _expected_hash():
    try:
        return json.loads(MANIFEST.read_text())['database']['sha256']
    except Exception:
        return None


def received_database_is_original():
    """True only when the tracked baseline database is present byte-for-byte."""
    expected = _expected_hash()
    if expected is None or not DATABASE.is_file():
        return False
    return hashlib.sha256(DATABASE.read_bytes()).hexdigest() == expected


def ensure_received_database():
    """Create a disposable compatible fixture if no database is present.

    Returns True when a fixture was generated by this call.
    """
    if received_database_is_original():
        return False
    if DATABASE.is_file():
        # A non-baseline file is present; leave it untouched and let the checks
        # report the real state rather than silently replacing data.
        return False
    env = os.environ.copy()
    env['EID_FIXTURE_DB'] = str(DATABASE)
    env['ADMIN_PASSWORD'] = 'deployment-fixture-strong-password'
    subprocess.run([sys.executable, '-c', _BUILD], cwd=ROOT / 'accounting-software', env=env, check=True)
    return True


ensure_received_database()
